// <auto-generated />
namespace BITCollege_TravisTaylor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class milestone4classes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(milestone4classes));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191522392_milestone4classes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
