//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEV3000Windows.ConcatenateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConcatenateService.IConcatenate")]
    public interface IConcatenate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConcatenate/DoWork", ReplyAction="http://tempuri.org/IConcatenate/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConcatenate/DoWork", ReplyAction="http://tempuri.org/IConcatenate/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConcatenate/NameAddress", ReplyAction="http://tempuri.org/IConcatenate/NameAddressResponse")]
        string NameAddress(string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConcatenate/NameAddress", ReplyAction="http://tempuri.org/IConcatenate/NameAddressResponse")]
        System.Threading.Tasks.Task<string> NameAddressAsync(string name, string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConcatenateChannel : ADEV3000Windows.ConcatenateService.IConcatenate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConcatenateClient : System.ServiceModel.ClientBase<ADEV3000Windows.ConcatenateService.IConcatenate>, ADEV3000Windows.ConcatenateService.IConcatenate {
        
        public ConcatenateClient() {
        }
        
        public ConcatenateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConcatenateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcatenateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcatenateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string NameAddress(string name, string address) {
            return base.Channel.NameAddress(name, address);
        }
        
        public System.Threading.Tasks.Task<string> NameAddressAsync(string name, string address) {
            return base.Channel.NameAddressAsync(name, address);
        }
    }
}
